const PrivacyPolicy = () => {
  return (
    <div>
      <h1 className="text-3xl font-bold text-center ">
        TERMS AND CONDITIONS FOR ISHN.XYZ
      </h1>
      <h3 className="text-xl font-bold text-center ">
        Last updated: 27-12-2022
      </h3>
      <div className="px-3 py-3">
        <p>
          Our link shortener app is an open-source project, which means that the
          source code is freely available for anyone to view, modify, and
          distribute. The app was built by an indie developer, working
          independently of a larger organization. We are committed to keeping
          the app open-source and do not have any plans to sell or profit from
          it. We have no intention of earning profits or selling any data
          collected through the app. We believe in the importance of
          transparency and the benefits of open-source software for users and
          developers alike.
        </p>
        <p>
          These terms and conditions (&quot;Terms&quot;) govern your access to
          and use of the link shortener app and related services (the
          &quot;Services&quot;) offered by ishn.xyz (&quot;we,&quot;
          &quot;us,&quot; or &quot;our&quot;). Please read these Terms carefully
          before using the Services. By accessing or using the Services, you
          agree to be bound by these Terms. If you do not agree to these Terms,
          do not use the Services.
        </p>
        <h2 className="text-xl font-bold">Account Registration</h2>
        <p>
          In order to use the Services, you must create an account and provide
          certain personal information,i.e, your name and email address. You are
          responsible for maintaining the confidentiality of your account and
          for restricting access to your device. You agree to accept
          responsibility for all activities that occur under your account.
        </p>
        <h2 className="text-xl font-bold">Use of the Services</h2>
        <p>
          The Services are intended for personal, non-commercial use only. You
          may not use the Services for any illegal or unauthorized purpose. You
          must not transmit any worms or viruses or any code of a destructive
          nature.
        </p>
        <p>
          You may not use the Services to:
          <ul>
            <li>
              - Engage in any activity that is illegal, harmful, or fraudulent.
            </li>
            <li>
              {" "}
              - Infringe upon the intellectual property rights of others.
            </li>
            <li> - Spam or send unsolicited messages.</li>
            <li> - Collect or store personal data about other users.</li>
          </ul>
          We reserve the right to terminate your access to the Services at any
          time and for any reason, without notice.
          <br />
          The developer of this project is not responsible for any kind of links
          generated by the users of this platform.
        </p>
        <h2 className="text-xl font-bold">Limitation of Liability</h2>
        <p>
          We will not be liable for any damages of any kind arising from the use
          of the Services, including, but not limited to, direct, indirect,
          incidental, punitive, and consequential damages.
        </p>
        <h2 className="text-xl font-bold">
          Changes to the Services and These Terms
        </h2>
        <p>
          We reserve the right to make changes to the Services and these Terms
          at any time. We will post any changes on this page and, if the changes
          are significant, we will provide a more prominent notice at the
          landing page as well. We encourage you to review these Terms whenever
          you access the Services to stay informed about our practices and your
          legal rights.
        </p>
        <h2 className="text-xl font-bold">Contact Us</h2>
        <p>
          If you have any questions about this Policy or our information
          practices, please contact me at{" "}
          <a href="mailto:hi@ishaanbedi.in">hi@ishaanbedi.in</a>.
        </p>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
