import Head from "next/head";
import Nav from "../components/Nav";
import Link from "next/link";

const Report = () => {
  return (
    <header>
      <main>
        <Head>
          <title>Report</title>
        </Head>
        <Nav />
        <div className="text-center mt-12">
          <h1 className="text-3xl text-center py-2 font-bold tracking-tight  sm:text-4xl">
            Report
          </h1>
          <div className="mx-2">
            <h3>
              If you find any offensive, inappropriate, or any other kind of
              abusive content on the website, created by any user, you can
              report it to me at{" "}
              <a
                className="underline underline-offset-4 font-semibold"
                href="mailto:hi@ishaanbedi.in"
              >
                hi@ishaanbedi.in
              </a>
            </h3>
            <h3>
              Reported content will be reviewed and deleted if found to be
              offensive or inappropriate.
            </h3>
            <h3>
              This project does not support, neither does it encourage any kind
              of links created which promote abuse, offense, or harassment of
              any kind.
            </h3>
            <h3>
              The developer of this project is not responsible for any kind of
              links generated by the users of this platform.
            </h3>
            <h3>
              I&apos;m constantly working on improving the security and safety
              of the platform, and I&apos;m always open to suggestions and
              feedback.
            </h3>
          </div>
        </div>
        <div className="text-center mt-12">
          <Link href="/">
            <span className="btn">Home</span>
          </Link>
        </div>
      </main>
    </header>
  );
};

export default Report;
