import Head from "next/head";
import Nav from "../../components/Nav";

const Report = () => {
  return (
    <header>
      <main>
        <Head>
          <title>Report</title>
        </Head>
        <Nav />

        <h1>Report</h1>
        <h3>
          If you find any offensive, inappropriate, or any other kind of abusive
          content on the website, created by any user, you can report it to me
          at <a href="mailto:hi@ishaanbedi.in">hi@ishaanbedi.in</a>
        </h3>
        <p>
          Reported content will be reviewed and deleted if found to be offensive
          or inappropriate.
          <br />
          <br />
          This project does not support, neither does it encourage any kind of
          links created which promote abuse, offense, or harassment of any kind.
          <br />
          <br />
          The developer of this project is not responsible for any kind of links
          generated by the users of this platform.
          <br />
          <br />
          I&apos;m constantly working on improving the security and safety of
          the platform, and I&apos;m always open to suggestions and feedback.
        </p>
      </main>
    </header>
  );
};

export default Report;
